import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  const [items, setItem] = useState(data)
  const [page, setPage] = useState(1)

  const next = async () => {
    const res = await fetch(`https://api.github.com/search/repositories?q=created:>2021-08-13&sort=stars&order=desc&page=${page + 1}`)
    const data = await res.json()
    setItem(data)
    setPage(page + 1)
    window.scrollTo(0,0)
  }

  const back = async () => {
    const res = await fetch(`https://api.github.com/search/repositories?q=created:>2021-08-13&sort=stars&order=desc&page=${page - 1}`)
    const data = await res.json()
    setItem(data)
    setPage(page - 1)
    window.scrollTo(0,0)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Repo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{textAlign: 'center', marginBottom: '2rem'}}>
          Github Repos
        </h1>

        <div>
          {
            items.items.map((item, key) => 
            <Card
              key={item?.id}
              name={item?.full_name}
              image={item.owner?.avatar_url}
              description={item?.description}
              stars={item?.stargazers_count}
              issues={item?.open_issues}
              user={item?.name}
              page={page}
            /> 
            )
          }
        </div>
      </main>

      <footer style={{display: 'flex'}}>
        <div style={{marginRight: '2rem', cursor: 'pointer'}} onClick={() => {page === 1 ? '' : back()}}>Back</div>
        <div>{page}</div>
        <div onClick={() => next()} style={{marginLeft: '2rem', cursor: 'pointer'}}>Next</div>
      </footer>
    </div>
  )
}

const Card = ({image, name, description, issues, stars, user}) => {
  return(
    <div style={{padding: '1rem', display: 'flex', marginBottom: '3rem', borderBottom: '.1px solid grey'}}>
      <div style={{marginRight: '1rem'}}>
        <Image src={image} width={150} height={150} alt='' />
      </div>
      <div style={{display: 'flex', flexDirection: 'column', justifyContent: 'flex-end'}}>
        <h3>{name}</h3>
        <p>{description}</p>
        <div style={{display: 'flex'}}>
          <div style={{marginRight: '1rem', fontSize: '.8rem', border: '1px solid black', borderRadius: '4px', padding: '.2rem .5rem'}}>Stars: {stars}k</div>
          <div style={{marginRight: '1rem', fontSize: '.8rem', border: '1px solid black', borderRadius: '4px', padding: '.2rem .5rem'}}>Issues: {issues}k</div>
          <div style={{marginRight: '1rem', fontSize: '.8rem', padding: '.2rem .5rem'}}>Submitted by {user}</div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://api.github.com/search/repositories?q=created:>2021-08-13&sort=stars&order=desc')
  const data = await res.json()
  
  return{
    props: { data }
  }
}